apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2026-02-09T17:19:33Z"
  generation: 3
  labels:
    app: webapp
    version: v1
  name: web-app-canary
  namespace: default
  resourceVersion: "35743"
  uid: b5967314-7d50-4a77-922f-1e00a4fc8ff3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-09T23:24:26+06:00"
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 8
  conditions:
  - lastTransitionTime: "2026-02-09T17:23:44Z"
    lastUpdateTime: "2026-02-09T17:23:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-09T17:19:34Z"
    lastUpdateTime: "2026-02-09T17:25:15Z"
    message: ReplicaSet "web-app-596cbb5648" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 8
  replicas: 8
  updatedReplicas: 8
