apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-canary
  name: web-canary
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: canary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
        version: canary
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources: {}
status: {}
