apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-pod
  name: resource-pod
  namespace: prod
spec:
  containers:
  - image: nginx
    name: resource-pod
    resources: 
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
         cpu: 1
         memory: 2Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
