apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-02-06T16:35:26Z"
  labels:
    run: metrics-pod
  name: metrics-pod
  namespace: monitoring
  resourceVersion: "19634"
  uid: 3bfc07e1-27d6-47d5-95f0-e328f42e6647
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: metrics-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-j9nlk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: monitor-sa
  serviceAccountName: monitor-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-j9nlk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T16:35:31Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T16:35:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T16:35:31Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T16:35:31Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-02-06T16:35:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cc119931e674fb2bcdfbd14d31f7802a50e3bedafbb74d6796950e2fd9d94d56
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:341bf0f3ce6c5277d6002cf6e1fb0319fa4252add24ab6a0e262e0056d313208
    lastState: {}
    name: metrics-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-02-06T16:35:31Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-j9nlk
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  phase: Running
  podIP: 10.244.0.28
  podIPs:
  - ip: 10.244.0.28
  qosClass: BestEffort
  startTime: "2026-02-06T16:35:26Z"
